const fs = require('fs');

const baseHtml = fs.readFileSync('admin-crm.html', 'utf8');
const topPart = baseHtml.substring(0, baseHtml.indexOf('<div class="dashboard-content">'));
const bottomPart = '</div></div><script src="js/sidebar-router.js"></script></body></html>';

function createPage(filename, title, contentHtml, scriptContent = '') {
    let pageTop = topPart.replace(/<h1>.*?<\/h1>/, '<h1>' + title + '</h1>');
    pageTop = pageTop.replace(/<title>.*?<\/title>/, '<title>' + title + ' | United Store</title>');
    
    const fullHtml = pageTop + 
            '<div class="dashboard-content">\n' +
            contentHtml +
            '</div>\n' +
            bottomPart + '\n' +
            (scriptContent ? '<script>' + scriptContent + '</script>' : '');

    fs.writeFileSync(filename, fullHtml);
}

const dashboardHtml = [
    '<div class="metrics-grid">',
    '    <div class="metric-card">',
    '        <div class="metric-icon revenue-icon"><i class="fas fa-money-bill-wave"></i></div>',
    '        <div class="metric-data">',
    '            <h4>Today&#39;s Revenue</h4>',
    '            <div class="metric-value">12.5M ₫</div>',
    '            <div class="metric-growth"><span class="growth-up"><i class="fas fa-arrow-up"></i> 8.4%</span> <span class="growth-text">vs yesterday</span></div>',
    '        </div>',
    '    </div>',
    '    <div class="metric-card">',
    '        <div class="metric-icon product-icon"><i class="fas fa-shopping-cart"></i></div>',
    '        <div class="metric-data">',
    '            <h4>New Orders</h4>',
    '            <div class="metric-value">42</div>',
    '            <div class="metric-growth"><span class="growth-up"><i class="fas fa-arrow-up"></i> 12.1%</span> <span class="growth-text">vs yesterday</span></div>',
    '        </div>',
    '    </div>',
    '    <div class="metric-card">',
    '        <div class="metric-icon user-icon"><i class="fas fa-users"></i></div>',
    '        <div class="metric-data">',
    '            <h4>Active Users</h4>',
    '            <div class="metric-value">1,204</div>',
    '            <div class="metric-growth"><span class="growth-up"><i class="fas fa-arrow-up"></i> 2.5%</span> <span class="growth-text">vs yesterday</span></div>',
    '        </div>',
    '    </div>',
    '    <div class="metric-card">',
    '        <div class="metric-icon" style="background: rgba(220, 38, 38, 0.1); color: #DC2626;"><i class="fas fa-exclamation-triangle"></i></div>',
    '        <div class="metric-data">',
    '            <h4>Low Stock Items</h4>',
    '            <div class="metric-value">8</div>',
    '            <div class="metric-growth"><span class="growth-down"><i class="fas fa-arrow-down"></i> Needs attention</span></div>',
    '        </div>',
    '    </div>',
    '</div>',
    '<div style="display: flex; gap: 24px;">',
    '    <div class="dashboard-section" style="flex: 2;">',
    '        <div class="section-header">',
    '            <div class="section-title"><i class="fas fa-chart-area"></i> Revenue Overview</div>',
    '        </div>',
    '        <div style="height: 300px; background: #fafafa; border: 1px dashed #ccc; display: flex; justify-content: center; align-items: center; border-radius: 8px; color: #888;">',
    '            <canvas id="revenueChart"></canvas>',
    '        </div>',
    '    </div>',
    '    <div class="dashboard-section" style="flex: 1;">',
    '        <div class="section-header">',
    '            <div class="section-title"><i class="fas fa-fire"></i> Top Selling Products</div>',
    '        </div>',
    '        <ul style="list-style: none; padding: 0; margin: 0;">',
    '            <li style="display: flex; align-items: center; gap: 15px; padding: 12px 0; border-bottom: 1px solid #eee;">',
    '                <img src="https://i.pinimg.com/736x/89/3e/32/893e32ca12e3f5d5b77ff0a59b6c00d8.jpg" style="width: 40px; height: 40px; object-fit: cover; border-radius: 8px;">',
    '                <div style="flex: 1;">',
    '                    <h4 style="font-size: 0.85rem; margin-bottom: 4px; color: #333;">Home Shirt 24/25</h4>',
    '                    <span style="font-size: 0.75rem; color: #888;">142 sales</span>',
    '                </div>',
    '                <div style="font-weight: 700; font-size: 0.9rem; color: #DA020E;">2.5M ₫</div>',
    '            </li>',
    '            <li style="display: flex; align-items: center; gap: 15px; padding: 12px 0; border-bottom: 1px solid #eee;">',
    '                <img src="https://i.pinimg.com/736x/67/da/75/67da75762c647b5ad3246ebc6046eef2.jpg" style="width: 40px; height: 40px; object-fit: cover; border-radius: 8px;">',
    '                <div style="flex: 1;">',
    '                    <h4 style="font-size: 0.85rem; margin-bottom: 4px; color: #333;">Away Shirt 24/25</h4>',
    '                    <span style="font-size: 0.75rem; color: #888;">98 sales</span>',
    '                </div>',
    '                <div style="font-weight: 700; font-size: 0.9rem; color: #DA020E;">2.5M ₫</div>',
    '            </li>',
    '            <li style="display: flex; align-items: center; gap: 15px; padding: 12px 0;">',
    '                <img src="https://i.pinimg.com/736x/e4/f0/a4/e4f0a4dbdcf7d6112d31da7e31d3f9ec.jpg" style="width: 40px; height: 40px; object-fit: cover; border-radius: 8px;">',
    '                <div style="flex: 1;">',
    '                    <h4 style="font-size: 0.85rem; margin-bottom: 4px; color: #333;">Training Top</h4>',
    '                    <span style="font-size: 0.75rem; color: #888;">65 sales</span>',
    '                </div>',
    '                <div style="font-weight: 700; font-size: 0.9rem; color: #DA020E;">1.5M ₫</div>',
    '            </li>',
    '        </ul>',
    '    </div>',
    '</div>'
].join('\\n');

const dashboardJs = "document.addEventListener('DOMContentLoaded', () => { const canvas = document.getElementById('revenueChart'); if (canvas) { const ctx = canvas.getContext('2d'); ctx.fillStyle = '#DA020E'; ctx.font = '16px Inter'; ctx.fillText('Biểu đồ doanh thu đang được cập nhật...', 50, 150); } });";
createPage('admin-dashboard.html', 'Dashboard Overview', dashboardHtml, dashboardJs);

const customersHtml = [
    '<div class="dashboard-section">',
    '    <div class="section-header">',
    '        <div class="section-title"><i class="fas fa-users"></i> Customers List</div>',
    '        <button class="btn-create"><i class="fas fa-file-export"></i> Export CSV</button>',
    '    </div>',
    '    <div class="table-responsive">',
    '        <table class="admin-table">',
    '            <thead>',
    '                <tr>',
    '                    <th style="width: 60px;">Avatar</th>',
    '                    <th>Customer Name</th>',
    '                    <th>Email Address</th>',
    '                    <th style="width: 100px; text-align: center;">Orders</th>',
    '                    <th style="width: 150px;">Total Spent</th>',
    '                    <th style="width: 120px;">Status</th>',
    '                    <th style="width: 100px; text-align: right;">Action</th>',
    '                </tr>',
    '            </thead>',
    '            <tbody>',
    '                <tr>',
    '                    <td><div class="avatar-img" style="width: 32px; height: 32px; font-size: 0.8rem;">JD</div></td>',
    '                    <td style="font-weight: 600;">John Doe</td>',
    '                    <td style="color: #666;">john.doe@gmail.com</td>',
    '                    <td style="text-align: center; font-weight: 600;">5</td>',
    '                    <td style="font-weight: 700; color: var(--admin-primary);">12.500.000 ₫</td>',
    '                    <td><span class="status-badge success">Active</span></td>',
    '                    <td style="text-align: right;"><button class="btn-action-icon"><i class="fas fa-eye"></i></button></td>',
    '                </tr>',
    '                <tr>',
    '                    <td><div class="avatar-img" style="width: 32px; height: 32px; font-size: 0.8rem; background: #6366f1;">SM</div></td>',
    '                    <td style="font-weight: 600;">Sarah Miller</td>',
    '                    <td style="color: #666;">sarah99@yahoo.com</td>',
    '                    <td style="text-align: center; font-weight: 600;">2</td>',
    '                    <td style="font-weight: 700; color: var(--admin-primary);">5.000.000 ₫</td>',
    '                    <td><span class="status-badge success">Active</span></td>',
    '                    <td style="text-align: right;"><button class="btn-action-icon"><i class="fas fa-eye"></i></button></td>',
    '                </tr>',
    '            </tbody>',
    '        </table>',
    '    </div>',
    '</div>'
].join('\\n');
createPage('admin-customers.html', 'Customers Management', customersHtml);

const inventoryHtml = [
    '<div class="dashboard-section">',
    '    <div class="section-header">',
    '        <div class="section-title"><i class="fas fa-tags"></i> Categories & Inventory</div>',
    '        <button class="btn-create"><i class="fas fa-plus"></i> Add Category</button>',
    '    </div>',
    '    <div class="table-responsive">',
    '        <table class="admin-table">',
    '            <thead>',
    '                <tr>',
    '                    <th style="width: 100px;">SKU</th>',
    '                    <th>Product Name</th>',
    '                    <th style="width: 150px;">Category</th>',
    '                    <th style="width: 150px; text-align: center;">Stock Level</th>',
    '                    <th style="width: 120px;">Status</th>',
    '                    <th style="width: 100px; text-align: right;">Update</th>',
    '                </tr>',
    '            </thead>',
    '            <tbody>',
    '                <tr>',
    '                    <td style="color: #888; font-weight: 500;">SKU-JER-001</td>',
    '                    <td style="font-weight: 600;">Home Shirt 24/25 - Size M</td>',
    '                    <td>Jerseys</td>',
    '                    <td style="text-align: center; font-weight: 700;">145</td>',
    '                    <td><span class="status-badge success">In Stock</span></td>',
    '                    <td style="text-align: right;"><button class="btn-action-icon"><i class="fas fa-edit"></i></button></td>',
    '                </tr>',
    '                <tr>',
    '                    <td style="color: #888; font-weight: 500;">SKU-JER-002</td>',
    '                    <td style="font-weight: 600;">Home Shirt 24/25 - Size L</td>',
    '                    <td>Jerseys</td>',
    '                    <td style="text-align: center; font-weight: 700; color: #dc2626;">4</td>',
    '                    <td><span class="status-badge danger" style="background: rgba(220,38,38,0.1); color: #dc2626;">Low Stock</span></td>',
    '                    <td style="text-align: right;"><button class="btn-action-icon"><i class="fas fa-edit"></i></button></td>',
    '                </tr>',
    '            </tbody>',
    '        </table>',
    '    </div>',
    '</div>'
].join('\\n');
createPage('admin-inventory.html', 'Inventory & Categories', inventoryHtml);

const discountsHtml = [
    '<div style="display: flex; gap: 24px;">',
    '    <div class="dashboard-section" style="flex: 2;">',
    '        <div class="section-header">',
    '            <div class="section-title"><i class="fas fa-ticket-alt"></i> Active Coupons</div>',
    '        </div>',
    '        <div class="table-responsive">',
    '            <table class="admin-table">',
    '                <thead>',
    '                    <tr>',
    '                        <th>Code</th>',
    '                        <th style="width: 100px;">Discount</th>',
    '                        <th style="width: 150px;">Expiry Date</th>',
    '                        <th style="width: 100px;">Status</th>',
    '                        <th style="width: 80px; text-align: right;">Action</th>',
    '                    </tr>',
    '                </thead>',
    '                <tbody>',
    '                    <tr>',
    '                        <td><span style="font-family: monospace; font-size: 1rem; font-weight: 700; background: #f3f4f6; padding: 4px 8px; border-radius: 4px;">WELCOME10</span></td>',
    '                        <td style="font-weight: 700; color: var(--admin-primary);">-10%</td>',
    '                        <td style="color: #666;">31/12/2026</td>',
    '                        <td><span class="status-badge success">Active</span></td>',
    '                        <td style="text-align: right;"><button class="btn-action-icon danger"><i class="fas fa-trash"></i></button></td>',
    '                    </tr>',
    '                </tbody>',
    '            </table>',
    '        </div>',
    '    </div>',
    '    <div class="dashboard-section" style="flex: 1;">',
    '        <div class="section-header">',
    '            <div class="section-title"><i class="fas fa-plus"></i> Generate Coupon</div>',
    '        </div>',
    '        <form style="display: flex; flex-direction: column; gap: 16px;">',
    '            <div>',
    '                <label style="display: block; font-size: 0.85rem; font-weight: 600; margin-bottom: 8px; color: #555;">Coupon Code</label>',
    '                <input type="text" placeholder="e.g. SUMMER24" style="width: 100%; padding: 10px 15px; border: 1px solid #ddd; border-radius: 8px;">',
    '            </div>',
    '            <div>',
    '                <label style="display: block; font-size: 0.85rem; font-weight: 600; margin-bottom: 8px; color: #555;">Discount (%)</label>',
    '                <input type="number" placeholder="10" min="1" max="100" style="width: 100%; padding: 10px 15px; border: 1px solid #ddd; border-radius: 8px;">',
    '            </div>',
    '            <button type="button" class="btn-create" style="margin-top: 10px; width: 100%; justify-content: center;">Create Coupon</button>',
    '        </form>',
    '    </div>',
    '</div>'
].join('\\n');
createPage('admin-discounts.html', 'Discounts & Coupons', discountsHtml);

const analyticsHtml = [
    '<div class="dashboard-section">',
    '    <div class="section-header">',
    '        <div class="section-title"><i class="fas fa-chart-bar"></i> Analytics & Reports</div>',
    '    </div>',
    '    <div style="height: 400px; background: #fafafa; border: 1px dashed #ccc; display: flex; flex-direction: column; justify-content: center; align-items: center; border-radius: 8px; color: #888;">',
    '        <i class="fas fa-tools" style="font-size: 3rem; margin-bottom: 15px; color: #cbd5e1;"></i>',
    '        <h3 style="color: #475569;">Advanced Analytics Engine</h3>',
    '        <p style="margin-top: 8px; font-size: 0.9rem;">Tích hợp Google Analytics và Chart.js đang được phát triển.</p>',
    '    </div>',
    '</div>'
].join('\\n');
createPage('admin-analytics.html', 'Store Analytics', analyticsHtml);

const settingsHtml = [
    '<div class="dashboard-section" style="max-width: 800px; margin: 0 auto;">',
    '    <div class="section-header">',
    '        <div class="section-title"><i class="fas fa-cog"></i> Store Configuration</div>',
    '    </div>',
    '    <div style="padding: 20px; background: #fff; border-radius: 8px; border: 1px solid #eee;">',
    '        <h4 style="font-size: 1rem; font-weight: 700; margin-bottom: 20px; border-bottom: 1px solid #eee; padding-bottom: 10px;">General Details</h4>',
    '        <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin-bottom: 30px;">',
    '            <div>',
    '                <label style="display: block; font-size: 0.85rem; font-weight: 600; margin-bottom: 8px;">Store Name</label>',
    '                <input type="text" value="United Store" style="width: 100%; padding: 10px 15px; border: 1px solid #ddd; border-radius: 8px;">',
    '            </div>',
    '            <div>',
    '                <label style="display: block; font-size: 0.85rem; font-weight: 600; margin-bottom: 8px;">Support Email</label>',
    '                <input type="email" value="support@manutd.com" style="width: 100%; padding: 10px 15px; border: 1px solid #ddd; border-radius: 8px;">',
    '            </div>',
    '        </div>',
    '        <div style="display: flex; justify-content: flex-end; gap: 12px; margin-top: 40px;">',
    '            <button type="button" class="btn-create" style="padding: 10px 24px;">Save Settings</button>',
    '        </div>',
    '    </div>',
    '</div>'
].join('\\n');
createPage('admin-settings.html', 'System Settings', settingsHtml);

console.log('All pages generated!');
