const fs = require('fs');

const htmlFile = 'admin-dashboard.html';
let content = fs.readFileSync(htmlFile, 'utf8');

const startMarker = '<!-- SUPABASE ADMIN SCRIPT -->';
const startIdx = content.indexOf(startMarker);

if (startIdx !== -1) {
    content = content.substring(0, startIdx);
} else {
    // If it doesn't exist, we just replace </body>
    content = content.replace('</body>', '');
}

const scriptLines = [
    '<!-- SUPABASE ADMIN SCRIPT -->',
    '<script src="https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2"></script>',
    '<script>',
    '    const _supabaseUrl = "";',
    '    const _supabaseKey = "";',
    '    let supabase = null;',
    '    if (_supabaseUrl && _supabaseKey) { supabase = supabase.createClient(_supabaseUrl, _supabaseKey); }',
    '    let currentUserRole = "";',
    '    let currentUserEmail = "";',
    '    async function checkAuthAndRole() {',
    '        if (!supabase) return false;',
    '        try {',
    '            const { data: { session }, error: sessionError } = await supabase.auth.getSession();',
    '            if (sessionError) throw sessionError;',
    '            if (!session) {',
    '                window.location.href = "index.html";',
    '                return false;',
    '            }',
    '            currentUserEmail = session.user.email;',
    '            const { data: userData, error: roleError } = await supabase.from("users").select("role").eq("email", currentUserEmail).single();',
    '            if (roleError) throw roleError;',
    '            currentUserRole = userData.role;',
    '            applyPermissions();',
    '            return true;',
    '        } catch (error) {',
    '            console.error("Lỗi xác thực:", error);',
    '            alert("Lỗi xác thực: " + error.message);',
    '            return false;',
    '        }',
    '    }',
    '    function applyPermissions() {',
    '        const addBtn = document.getElementById("btn-add-product");',
    '        if (currentUserRole !== "admin") {',
    '            if (addBtn) addBtn.style.display = "none";',
    '            const badge = document.createElement("div");',
    '            badge.innerHTML = "View Only Mode - Cấp quyền Admin để chỉnh sửa";',
    '            badge.style.position = "fixed";',
    '            badge.style.bottom = "20px";',
    '            badge.style.right = "20px";',
    '            badge.style.backgroundColor = "#ff4444";',
    '            badge.style.color = "white";',
    '            badge.style.padding = "10px 15px";',
    '            badge.style.borderRadius = "5px";',
    '            badge.style.zIndex = "9999";',
    '            badge.style.fontWeight = "bold";',
    '            badge.style.boxShadow = "0 2px 5px rgba(0,0,0,0.2)";',
    '            document.body.appendChild(badge);',
    '        }',
    '    }',
    '    async function fetchProducts() {',
    '        if (!supabase) return;',
    '        try {',
    '            const { data, error } = await supabase.from("products").select("*");',
    '            if (error) throw error;',
    '            const tbody = document.getElementById("product-table-body") || document.querySelector("tbody");',
    '            if (!tbody) return;',
    '            tbody.innerHTML = "";',
    '            data.forEach(product => {',
    '                const tr = document.createElement("tr");',
    '                let actionCell = "";',
    '                if (currentUserRole === "admin") {',
    '                    actionCell = "<td class=\\"action-cell\\"><button class=\\"btn-edit\\" onclick=\\"alert(\\'Tính năng Edit đang phát triển!\\')\\"><i class=\\"fa-solid fa-pen\\"></i> Edit</button> <button class=\\"btn-delete\\" onclick=\\"deleteProduct(\\'" + product.id + "\\')\\"><i class=\\"fa-solid fa-trash\\"></i> Delete</button></td>";',
    '                } else {',
    '                    actionCell = "<td class=\\"action-cell\\"><span style=\\"color: gray; font-size: 0.85rem;\\">View Only</span></td>";',
    '                }',
    '                tr.innerHTML = "<td><img src=\\"" + product.image_url + "\\" alt=\\"" + product.name + "\\" class=\\"table-img\\" onerror=\\"this.src=\\'images/placeholder.jpg\\'\\"></td>" +',
    '                               "<td>" + product.name + "</td>" +',
    '                               "<td>(N/A)</td>" +',
    '                               "<td>$" + product.price + "</td>" +',
    '                               "<td><span class=\\"status-badge success\\">In Stock</span></td>" +',
    '                               actionCell;',
    '                tbody.appendChild(tr);',
    '            });',
    '        } catch (error) {',
    '            alert("Lỗi tải dữ liệu sản phẩm: " + error.message);',
    '        }',
    '    }',
    '    async function deleteProduct(id) {',
    '        if (currentUserRole !== "admin") { return alert("Bạn không có quyền thực hiện thao tác này!"); }',
    '        if (!confirm("Bạn có chắc chắn muốn xóa sản phẩm này khỏi Database?")) return;',
    '        try {',
    '            const { error } = await supabase.from("products").delete().eq("id", id);',
    '            if (error) throw error;',
    '            alert("Xóa sản phẩm thành công!");',
    '            fetchProducts();',
    '        } catch (error) {',
    '            alert("Lỗi xóa sản phẩm: " + error.message);',
    '        }',
    '    }',
    '    document.addEventListener("DOMContentLoaded", async () => {',
    '        const isAuthorized = await checkAuthAndRole();',
    '        if (!isAuthorized) return;',
    '        fetchProducts();',
    '        const addForm = document.getElementById("add-product-form");',
    '        if (addForm) {',
    '            addForm.addEventListener("submit", async (e) => {',
    '                e.preventDefault();',
    '                if (currentUserRole !== "admin") { return alert("Bạn không có quyền thực hiện thao tác này!"); }',
    '                if (!supabase) { alert("Chưa kết nối Supabase!"); return; }',
    '                const nameInput = document.getElementById("prod-name");',
    '                const priceInput = document.getElementById("prod-price");',
    '                const imageInput = document.getElementById("prod-image");',
    '                if (!nameInput || !priceInput || !imageInput) { alert("Lỗi: Form thiếu các ô nhập"); return; }',
    '                try {',
    '                    const { error } = await supabase.from("products").insert([{ name: nameInput.value, price: priceInput.value, image_url: imageInput.value }]);',
    '                    if (error) throw error;',
    '                    alert("Thêm sản phẩm thành công!");',
    '                    const modal = document.getElementById("addProductModal");',
    '                    if (modal) modal.style.display = "none";',
    '                    addForm.reset();',
    '                    fetchProducts();',
    '                } catch (error) {',
    '                    alert("Lỗi thêm sản phẩm: " + error.message);',
    '                }',
    '            });',
    '        }',
    '    });',
    '</script>',
    '</body>',
    '</html>'
];

content += scriptLines.join('\\n');
fs.writeFileSync(htmlFile, content, 'utf8');
console.log('Update admin-dashboard.html RBAC successfully.');
